# Redis configuration for local ChirpStack development.
bind 0.0.0.0
protected-mode no
port 6379
timeout 0
tcp-keepalive 300
save 900 1
save 300 10
save 60 10000
appendonly yes
dir /data
loglevel notice
