persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

listener 1883
allow_anonymous false

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json


# - escuche en el puerto 1883
#- no permita conexiones anónimas
#- use usuario y contraseña
#- use ACL para controlar topics
#- guarde persistencia en /mosquitto/data
#- mande logs a stdout para verlos con docker logs