persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

listener 1883
allow_anonymous false

password_file /mosquitto/auth/passwordfile
acl_file /mosquitto/auth/aclfile


# - escuche en el puerto 1883
#- no permita conexiones anónimas
#- use usuario y contraseña
#- use ACL para controlar topics
#- guarde persistencia en /mosquitto/data
#- mande logs a stdout para verlos con docker logs