[general]
log_level="info"

[chirpstack]
api_host="$CHIRPSTACK_API_HOST"
api_port=$CHIRPSTACK_API_PORT
api_token="$CHIRPSTACK_API_TOKEN"
tenant_id="$CHIRPSTACK_TENANT_ID"
application_id="$CHIRPSTACK_APPLICATION_ID"
device_profile_id="$CHIRPSTACK_DEVICE_PROFILE_ID"

[mqtt]
server="ssl://$EMQX_MQTT_HOST:$EMQX_MQTT_PORT"
username="$EMQX_MQTT_USERNAME"
password="$EMQX_MQTT_PASSWORD"

[gateway]
id="$CHIRPSTACK_GATEWAY_ID"
event_topic_template="$LORAWAN_TOPIC_PREFIX/gateway/{{ .GatewayID }}/event/{{ .Event }}"
command_topic_template="$LORAWAN_TOPIC_PREFIX/gateway/{{ .GatewayID }}/command/{{ .Command }}"
downlink_tx_ack_delay="$SIM_ACK_DELAY"

[device]
dev_eui="$CHIRPSTACK_DEV_EUI"
join_eui="$CHIRPSTACK_JOIN_EUI"
app_key="$CHIRPSTACK_APP_KEY"
otaa_delay="$SIM_OTAA_DELAY"
uplink_interval="$SIM_UPLINK_INTERVAL"
confirmed_uplink=$SIM_CONFIRMED_UPLINK
f_port=10
frequency=$SIM_TX_FREQUENCY
bandwidth=$SIM_TX_BANDWIDTH
spreading_factor=$SIM_TX_SPREADING_FACTOR

[scenario]
name="$SIM_SCENARIO"
duration="$SIM_DURATION"
shape_hex="$SIM_SHAPE_HEX"
jitter_meters=$SIM_JITTER_METERS
altitude_meters=$SIM_ALTITUDE_METERS
accuracy_meters=$SIM_ACCURACY_METERS
battery_start=$SIM_BATTERY_START
