PROTOCOL_VERSION_V1 = 0x01

COMMAND_FPORT = 10
LOCATION_UPLINK_FPORT = 10
STATUS_UPLINK_FPORT = 11
COMMAND_ACK_FPORT = 20

COMMAND_TYPE_SET_REPORT_INTERVAL = 0x01
COMMAND_TYPE_WARNING_SOUND = 0x02
COMMAND_TYPE_STOP_CORRECTION = 0x03
COMMAND_TYPE_REQUEST_STATUS = 0x04

LOCATION_MESSAGE_TYPE = 0x01
STATUS_MESSAGE_TYPE = 0x02

GPS_FIX_NO_FIX = 0x00
GPS_FIX_GPS = 0x01
GPS_FIX_DGPS = 0x02
GPS_FIX_ESTIMATED = 0x03

COMMAND_ACK_STATUS_EXECUTED = 0x01
COMMAND_ACK_STATUS_REJECTED = 0x02
COMMAND_ACK_STATUS_FAILED = 0x03
COMMAND_ACK_STATUS_EXPIRED = 0x04
COMMAND_ACK_STATUS_DUPLICATE = 0x05

COMMAND_ACK_ERROR_NO_ERROR = 0x00
COMMAND_ACK_ERROR_UNKNOWN_COMMAND_TYPE = 0x01
COMMAND_ACK_ERROR_INVALID_PAYLOAD = 0x02
COMMAND_ACK_ERROR_BUSY = 0x03
COMMAND_ACK_ERROR_LOW_BATTERY = 0x04
COMMAND_ACK_ERROR_HARDWARE_ERROR = 0x05
COMMAND_ACK_ERROR_COMMAND_EXPIRED_ON_DEVICE = 0x06

LOCATION_PAYLOAD_LENGTH_V1 = 15
STATUS_PAYLOAD_LENGTH_V1 = 8
COMMAND_ACK_PAYLOAD_LENGTH_V1 = 5
