# PostgreSQL configuration for local ChirpStack development.
listen_addresses = '*'
max_connections = 100
shared_buffers = 128MB
dynamic_shared_memory_type = posix
wal_level = replica
log_destination = 'stderr'
logging_collector = off
log_connections = on
log_disconnections = on
log_statement = 'none'
