"""2 new attributes to TelemetryMessage

Revision ID: 4511f23b597d
Revises: be6f45e50817
Create Date: 2026-04-22 19:02:13.243733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4511f23b597d'
down_revision: Union[str, Sequence[str], None] = 'be6f45e50817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_messages', sa.Column('processed', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('telemetry_messages', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_messages', 'error_message')
    op.drop_column('telemetry_messages', 'processed')
    # ### end Alembic commands ###
