"""soft delete column all models

Revision ID: e0f71f0db473
Revises: f832219bc3af
Create Date: 2026-05-02 23:37:52.753693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f71f0db473'
down_revision: Union[str, Sequence[str], None] = 'f832219bc3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    tables = (
        'assets',
        'clients',
        'device_credentials',
        'devices',
        'locations',
        'telemetry_messages',
    )

    for table_name in tables:
        op.add_column(
            table_name,
            sa.Column(
                'deleted',
                sa.String(length=1),
                nullable=False,
                server_default='N',
            ),
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_messages', 'deleted')
    op.drop_column('locations', 'deleted')
    op.drop_column('devices', 'deleted')
    op.drop_column('device_credentials', 'deleted')
    op.drop_column('clients', 'deleted')
    op.drop_column('assets', 'deleted')
    # ### end Alembic commands ###
