"""initial migration

Revision ID: e164566bafe4
Revises: 
Create Date: 2026-04-21 19:22:38.215926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e164566bafe4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_client')
    )
    op.create_table('assets',
    sa.Column('id_asset', sa.Integer(), nullable=False),
    sa.Column('type_aseet', sa.String(), nullable=False),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_asset'),
    sa.UniqueConstraint('serial')
    )
    op.create_table('devices',
    sa.Column('id_device', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('ON', 'OFF', name='devicestate'), nullable=False),
    sa.Column('comunication_protocol', sa.Enum('HTTP', 'MQTT', name='devicecomunicationprotocol'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id_asset'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_device'),
    sa.UniqueConstraint('serial')
    )
    op.create_table('device_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id_device'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.String(), nullable=False),
    sa.Column('long', sa.String(), nullable=False),
    sa.Column('altitude', sa.String(), nullable=False),
    sa.Column('accuarcy', sa.String(), nullable=False),
    sa.Column('geometry', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id_device'], ),
    sa.PrimaryKeyConstraint('id_location')
    )
    op.create_table('telemetry_messages',
    sa.Column('id_telemetry', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('recived_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.String(), nullable=False),
    sa.Column('protocol', sa.Enum('HTTP', 'MQTT', name='devicecomunicationprotocol'), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id_device'], ),
    sa.PrimaryKeyConstraint('id_telemetry')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_messages')
    op.drop_table('locations')
    op.drop_table('device_credentials')
    op.drop_table('devices')
    op.drop_table('assets')
    op.drop_table('clients')
    # ### end Alembic commands ###
