"""improve device mqtt credentials

Revision ID: 10718bead5ab
Revises: 9c282ac96d95
Create Date: 2026-05-05 11:17:49.167881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10718bead5ab'
down_revision: Union[str, Sequence[str], None] = '9c282ac96d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


mqtt_provider_enum = sa.Enum('EMQX_CLOUD', 'MOSQUITTO', name='mqttprovider')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    mqtt_provider_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('device_credentials', sa.Column('mqtt_password_hash', sa.String(), nullable=True))
    op.add_column('device_credentials', sa.Column('mqtt_password_encrypted', sa.String(), nullable=True))
    op.add_column('device_credentials', sa.Column('mqtt_provider', mqtt_provider_enum, nullable=True))
    op.create_unique_constraint('uq_device_credentials_mqtt_password_hash', 'device_credentials', ['mqtt_password_hash'])
    op.create_unique_constraint('uq_device_credentials_mqtt_password_encrypted', 'device_credentials', ['mqtt_password_encrypted'])
    op.drop_column('device_credentials', 'mqtt_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_credentials', sa.Column('mqtt_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_device_credentials_mqtt_password_encrypted', 'device_credentials', type_='unique')
    op.drop_constraint('uq_device_credentials_mqtt_password_hash', 'device_credentials', type_='unique')
    op.drop_column('device_credentials', 'mqtt_provider')
    op.drop_column('device_credentials', 'mqtt_password_encrypted')
    op.drop_column('device_credentials', 'mqtt_password_hash')
    mqtt_provider_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
