"""mqtt device credentials

Revision ID: 9c282ac96d95
Revises: e0f71f0db473
Create Date: 2026-05-03 18:10:26.222095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c282ac96d95'
down_revision: Union[str, Sequence[str], None] = 'e0f71f0db473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_credentials', sa.Column('mqtt_username', sa.String(), nullable=True))
    op.add_column('device_credentials', sa.Column('mqtt_password', sa.String(), nullable=True))
    op.add_column('device_credentials', sa.Column('location_topic', sa.String(), nullable=True))
    op.add_column('device_credentials', sa.Column('status_topic', sa.String(), nullable=True))
    op.add_column('device_credentials', sa.Column('heartbeat_topic', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'device_credentials', ['mqtt_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_credentials', type_='unique')
    op.drop_column('device_credentials', 'heartbeat_topic')
    op.drop_column('device_credentials', 'status_topic')
    op.drop_column('device_credentials', 'location_topic')
    op.drop_column('device_credentials', 'mqtt_password')
    op.drop_column('device_credentials', 'mqtt_username')
    # ### end Alembic commands ###
